# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "trusty64"
  # vagrant issues #1673..fixes hang with configure_networks
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.provider :libvirt do |domain|
    domain.memory = 256
    domain.nested = true
  end

  (1..7).each do |i|
     config.vm.define "host#{i}" do |node|
      node.vm.hostname = "host#{i}"
      # not a fan of the synced_folder feature
      node.vm.synced_folder '.', '/vagrant', :disabled => true
      node.vm.network :private_network,
        :dev => 'virbr0',
        :type => 'bridge',
        :ip => '192.168.121.24#{i}', # bogus IP so tha vagrant-libvirt can create virt_network
        :auto_config => false,
        #:libvirt__forward_mode => 'veryisolated',
        #:libvirt__dhcp_enabled => false,
        :libvirt__network_name => 'vagrant-libvirt'
    end
  end
end
