- name: Determining swarm manager status
  shell: >
      docker -H :4000 info 2>/dev/null | egrep '^Role: ' | cut -d ' ' -f2 | grep -xq '^[primary|replica]*$' && echo 'active' || echo 'passive'
  register: swarm_status

- name: Creating swarm_manager_operational group
  add_host:
    hostname: "{{ item }}"
    groups: swarm_manager_operational
  with_items: "{{ ansible_play_hosts | default(play_hosts) }}"
  when: "'active' in hostvars[item].swarm_status.stdout_lines and 'swarm_manager_operational' not in group_names"
  run_once: true
